name: Run PaddleOCR

on:
  workflow_dispatch:
  push:
    paths:
      - 'input.png'

jobs:
  ocr:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1 libglib2.0-0

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install paddlepaddle paddleocr pyjson

    - name: Run OCR processing
      run: python ocr.py

    - name: Upload result
      uses: actions/upload-artifact@v3
      with:
        name: ocr-result
        path: |
          output.json
          input.png
