name: Python OCR Pipeline

on:
  workflow_dispatch: # 手动触发配置

jobs:
  run-ocr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1  # OpenCV所需系统依赖

    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install imgocr onnxruntime numpy Pillow opencv-python

    - name: Run OCR script
      run: python ocr.py
      
    - name: Upload result
      uses: actions/upload-artifact@v3
      with:
        name: ocr-result
        path: result.json
